[package]
name = "yaml2json"
version = "0.1.0"
authors = ["Nathan Essex <nathan@essex.id.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
