[package]
name = "yaml2json-bin"
description = "Utility to convert YAML files to JSON"
version = "0.2.0"
authors = ["Nathan Essex <nathan@essex.id.au>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
anyhow = "1.0.34"
yaml-split = { path = "../yaml-split" }
yaml2json = { path = "../yaml2json" }
