[package]
name = "yaml2json-rs"
description = "Convert YAML documents to JSON"
version = "0.2.1"
authors = ["Nathan Essex <nathan@essex.id.au>"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
thiserror = "1.0.22"
