[package]
name = "yaml-split"
description = "splits a YAML string into separate files"
version = "0.2.0"
authors = ["Nathan Essex <nathan@essex.id.au>"]
edition = "2018"

[dependencies]
thiserror = "1.0.22"