[package]
name = "yaml-split"
description = "provides an iterator over individual YAML documents in a YAML file or stream"
version = "0.2.0"
authors = ["Nathan Essex <nathan@essex.id.au>"]
edition = "2018"

[dependencies]
thiserror = "1.0.22"